services:
  frontend:
    build:
      dockerfile: apps/frontend/Dockerfile
      context: .
      args:
        RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
        BASE_URL: ${BASE_URL}
        WS_URL: ${WS_URL}
    image: ${REGISTRY}/lems-frontend:${IMAGE_TAG}
    ports:
      - '4200:4200'
    env_file:
      - apps/frontend/.env.production

  backend:
    build:
      dockerfile: apps/backend/Dockerfile
      context: .
      args:
        DIGITALOCEAN_KEY: ${DIGITALOCEAN_KEY}
        DIGITALOCEAN_SECRET: ${DIGITALOCEAN_SECRET}
        JWT_SECRET: ${JWT_SECRET}
        MONGODB_URI: ${MONGODB_URI}
        MONGO_CA_CERTIFICATE: ${MONGO_CA_CERTIFICATE}
        RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
    image: ${REGISTRY}/lems-backend:${IMAGE_TAG}
    ports:
      - '3333:3333'
    env_file:
      - apps/backend/.env.production
    volumes:
      - /root/mongo-ca-certificate.crt:/root/mongo-ca-certificate.crt

networks:
  default:
    name: lems_network
    driver: bridge
